# Numpy for data analysis


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr[1])
print(arr[4]+arr[2])

[1 2 3 4 5]
2
8


In [15]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
print('3rd element on 2nd dim:' , arr[1,2])

2nd element on 1st dim:  2
3rd element on 2nd dim: 8


In [40]:
#Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('last element on 1st dim: ', arr[0, -1])
print('2ndlast element on 2nd dim:' , arr[1,-2])

last element on 1st dim:  5
2ndlast element on 2nd dim: 9


In [3]:
print(np.__version__)

1.19.2


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr = np.array(42)

print(arr)

42


In [35]:
#Access the third element of the second array of the first array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print(arr[0,1,2])

#Access the first element of the second array of the second array:
print(arr[1,1,0])

#Access the third element of the first array of the second array:
print(arr[1,0,2])
#Access the third element of the first array of the first array:
print(arr[0,0,2])
#Access the 2nd element of the second array of the second array:
print(arr[1,1,1])
#Access the 2nd element of the first array of the second array:
print(arr[1,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
10
9
3
11
8


In [47]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

0
1
2
3
()
(5,)
(2, 3)
(2, 2, 3)


In [12]:
array=np.array([1,4,5,43,3,2], ndmin=5)
print(array)
print('dimension is:', array.ndim)
print(array[0])



[[[[[ 1  4  5 43  3  2]]]]]
dimension is: 5
[[[[ 1  4  5 43  3  2]]]]


In [43]:
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#Slice elements from index 1 to index 5 from the following array:
print(arr[2:5])
#Slice elements from index 2 to end of the following array:
print(arr[2:])
#Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[2 3 4 5]
[3 4 5]
[3 4 5 6 7]
[1 2 3 4]


In [46]:
#negative slicing: Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
print(arr[-5:-2])

[5 6]
[3 4 5]


In [51]:
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[1:6:4])


[2 4]
[2 6]


In [52]:
#Return every other element from the entire array
print(arr[::2])

[1 3 5 7]


In [54]:
print(arr[::3])
print(arr[::4])

[1 4 7]
[1 5]


In [57]:
#SLICING 2d-ARRAY From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0,2:4])

[7 8 9]
[3 4]


In [61]:
#From both elements, return index 2:

print(arr[0:2, 2])
print(arr[0:1, 3])


[3 8]
[4]


In [62]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [1]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [12]:
import numpy as np
arr = np.array([1, -2, 3.6, 4], dtype='S')
print(arr)

print(arr.dtype)


[b'1' b'-2' b'3.6' b'4']
|S3


In [23]:
#Creating Arrays With a Defined Data Type
arr=np.array([2,4,6,8,8], dtype='f')
print(arr)
print(arr.dtype)

[2. 4. 6. 8. 8.]
float32


In [18]:
#Create an array with data type 4 bytes integer:#Creating Arrays With a Defined Data Type
arr=np.array([2,4,6,8,8], dtype='i4')
print(arr)
print(arr.dtype)

[2 4 6 8 8]
int32


In [25]:
#A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [29]:
#Converting Data Type on Existing Arrays
import numpy as np
arr = np.array([1, -2, 3.6,0,0, 4])
newarr= arr.astype('i')
newarr1= arr.astype('f')
newarr2 = arr.astype(bool)
print(arr)

print(newarr)
print(newarr1)
print(newarr2)


[ 1.  -2.   3.6  0.   0.   4. ]
[ 1 -2  3  0  0  4]
[ 1.  -2.   3.6  0.   0.   4. ]
[ True  True  True False False  True]


In [30]:
#Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [32]:
#Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [33]:
#print the value of the base attribute to check if an array owns it's data or not:
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[42  2  3  4  5]


In [37]:
#Get the Shape of an Array
arr=np.array([[1,2,3,4,8],[5,6,9,7,8]])
print(arr.shape)

(2, 5)


In [42]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 8, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 8 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [44]:
import numpy as np

arr = np.array([1,4,7,7,8, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 4 7 7 8 3 4]]]]]
shape of array : (1, 1, 1, 1, 7)


In [64]:
#Convert the following 1-D array with 12 elements into a 2-D array.The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)

newarry = arr.reshape(2,6)

print(newarr)
print(newarry)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [1]:
#Convert the following 1-D array with 12 elements into a 3-D array.The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 2, 2)
newarr1 = arr.reshape(2, 3, 2)
print(newarr)

print(newarr1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
#We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array 
import numpy as np
d = np.array([11,12,13,14,15,16,17,18])
r=d.reshape(2,4)
print(r)


[[11 12 13 14]
 [15 16 17 18]]


In [18]:
#Check if the returned array is a copy or a view:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [28]:
#1 unknown dimendion =-1, Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [1]:
#Iterate on the elements of the following 1-D array:
import numpy as np
arr=np.array([1,2,3,4])
for x in arr:
    print(x)

1
2
3
4


In [3]:
#In a 2-D array it will go through all the rows.
import numpy as np
arr=np.array([[1,2,3,4],[8,9,6,7]])
for x in arr:
    print(x)

#Iterate on each scalar element of the 2-D array:
for x in arr:
    for y in x:
        print(y)

[1 2 3 4]
[8 9 6 7]
1
2
3
4
8
9
6
7


In [8]:
#In a 3-D array it will go through all the 2-D arrays.
arr=np.array([[[1,2,3,4],[8,9,6,7]],[[10,11,12,13],[14,15,16,17]]])
for x in arr:
            print(x)

[[1 2 3 4]
 [8 9 6 7]]
[[10 11 12 13]
 [14 15 16 17]]


In [9]:
#Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
     for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
#Iterating Arrays Using nditer()
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
#Iterating Array With Different Data Types
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
                   print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [34]:
#Iterate through every scalar element of the 2D array skipping 1 element:
arr= np.array([[1,2,3,4],[6,7,8,9]])
for x in np.nditer(arr[:,::2]): 
    print(x)

1
3
6
8


In [43]:
#Iterate through every scalar element of the 2D array skipping 1 element:
arr= np.array([[1,2,3,4,6,7,8,9]])
for x in np.nditer(arr[:,::3]): 
    print(x)

1
4
8


In [71]:
##Iterate through every scalar element of the 3D array skipping 1 element:
arr=np.array([[[1,2,3,4],[8,9,6,7]],[[10,11,12,13],[14,15,16,17]]])
for x in np.nditer(arr[:,::1,::2]):
            print(x)

1
3
8
6
10
12
14
16


In [66]:
#Enumerated Iteration Using ndenumerate(), mentioning sequence number
arr= np.array([[1,2,3,4],[6,7,8,9]])
for index,x in np.ndenumerate(arr): 
    print(index,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9


In [72]:
arr=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
for x in np.nditer(arr[:,::2]):
            print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
4
6
7
9


In [73]:
#Join two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [81]:
#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [85]:
# Joining Arrays Using Stack Functions,Stacking is same as concatenation, the only difference is that stacking is done along a new axis.arr1 = np.array([1, 2, 3])
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [105]:
# Joining Arrays Using Stack Functions,Stacking is same as concatenation, the only difference is that stacking is done along a new axis.arr1 = np.array([1, 2, 3])
arr1 = np.array([[1, 2, 3],[8,9,0]])
arr2 = np.array([[4, 5, 6],[2,8,1]])
arr = np.stack((arr1, arr2))
arrx= np.hstack((arr1, arr2))
arry= np.vstack((arr1,arr2))
ar= np.dstack((arr1,arr2))
print(arr)
print(arrx)
print(arry)
print(ar)

[[[1 2 3]
  [8 9 0]]

 [[4 5 6]
  [2 8 1]]]
[[1 2 3 4 5 6]
 [8 9 0 2 8 1]]
[[1 2 3]
 [8 9 0]
 [4 5 6]
 [2 8 1]]
[[[1 4]
  [2 5]
  [3 6]]

 [[8 2]
  [9 8]
  [0 1]]]


In [86]:
#Stacking Along Rows,NumPy provides a helper function: hstack() to stack along rows.
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [87]:
#Stacking Along Column,NumPy provides a helper function: vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [88]:
#Stacking Along Height (depth),NumPy provides a helper function: dstack() to stack along height, which is the same as depth

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


In [107]:
#Split the array in 3 parts:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [108]:
#Access the splitted arrays:
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5]


In [2]:
import numpy as np
arr= np.array([[1,2,3,4],[6,7,8,9]])
new=np.array_split(arr,2)
print(new)

[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]])]


In [3]:
#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [7]:
#specify which axis you want to do the split around.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr,3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [18]:
#specify which axis you want to do the split around.
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])

newarr = np.array_split(arr,3,axis=1)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]]), array([[[13, 14, 15],
        [16, 17, 18]]])]


In [19]:
#specify which axis you want to do the split around.
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])
arr = np.array([[[1,2,3,4],[8,9,6,7]],[[10,11,12,13],[14,15,16,17]]])
newarr = np.array_split(arr,3,axis=2)

print(newarr)

[array([[[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]])]


In [25]:
#specify which axis you want to do the split around.
arr = np.array([[[1,2,3,4],[8,9,6,7]],[[10,11,12,13],[14,15,16,17]]])
newarr = np.array_split(arr,2,axis=2)

print(newarr)

[array([[[ 1,  2],
        [ 8,  9]],

       [[10, 11],
        [14, 15]]]), array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [16, 17]]])]


In [20]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [26]:
#Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int32),)


In [27]:
#Find the indexes where the values are odd:
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4], dtype=int32),)


In [34]:
#Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])

x1 = np.searchsorted(arr, 9)
#Find the indexes where the value 7 should be inserted, starting from the right:
x2=np.searchsorted(arr,7,side='right')
print(x1)
print(x2)

3
2


In [40]:
#multiple values, Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7,8,9])

x = np.searchsorted(arr, [2, 4,6,9])

print(x)

[1 2 3 5]


In [41]:
#Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [42]:
#Sort a 2-D array:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [43]:
#Create an array from the elements on index 0 and 2:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [46]:
arr=np.array(['ali','bill','jay','nia','trw','moosh'])
d=[False,True,True,False,False,True]
new=arr[d]
print(new)

['bill' 'jay' 'moosh']


In [59]:
#FILTERING BASED ON CONDITIONS
import numpy as np

arr = np.array([41, 45, 43, 44,47,48,40])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]


print(filter_arr)
print(newarr)


[False, True, True, True, True, True, False]
[45 43 44 47 48]


In [62]:
#Create a filter array that will return only even elements from the original array:
arr=np.array([1,2,3,4,5,6,7,9])
empty=[]
for element in arr:
    if element%2==0:
        empty.append(True)
    else:
        empty.append(False)
filter_array=arr[empty]
        
print(empty)
print(filter_array)    

[False, True, False, True, False, True, False, False]
[2 4 6]


In [64]:
#Creating Filter Directly From Array,create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([1,2,3,4,5,6,7,9])

filter_arr = arr%2==0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False False]
[2 4 6]
